/** @file */

#ifndef MCA_COLL_SHARM_ALG_TYPES_H
#define MCA_COLL_SHARM_ALG_TYPES_H

#define COLL_SHARM_BARRIER_ALG_SENSE_REVERSING 1
#define COLL_SHARM_BARRIER_ALG_CICO            2

#define COLL_SHARM_BCAST_ALG_CICO  1
#define COLL_SHARM_BCAST_ALG_CMA   11
#define COLL_SHARM_BCAST_ALG_XPMEM 21

#define COLL_SHARM_SCATTER_ALG_CICO  1
#define COLL_SHARM_SCATTER_ALG_CMA   11
#define COLL_SHARM_SCATTER_ALG_XPMEM 21

#define COLL_SHARM_SCATTERV_ALG_CICO  1
#define COLL_SHARM_SCATTERV_ALG_CMA   11
#define COLL_SHARM_SCATTERV_ALG_XPMEM 21

#define COLL_SHARM_GATHER_ALG_CICO  1
#define COLL_SHARM_GATHER_ALG_CMA   11
#define COLL_SHARM_GATHER_ALG_XPMEM 21

#define COLL_SHARM_GATHERV_ALG_CICO  1
#define COLL_SHARM_GATHERV_ALG_CMA   11
#define COLL_SHARM_GATHERV_ALG_XPMEM 21

#define COLL_SHARM_REDUCE_ALG_FLAT_TREE 1
#define COLL_SHARM_REDUCE_ALG_KNOMIAL   2
#define COLL_SHARM_REDUCE_ALG_CMA       11
#define COLL_SHARM_REDUCE_ALG_XPMEM     21

#define COLL_SHARM_ALLREDUCE_ALG_REDUCE_BCAST            1
#define COLL_SHARM_ALLREDUCE_ALG_FLAT_TREE               2
#define COLL_SHARM_ALLREDUCE_ALG_NATIVE_REDUCE_BROADCAST 3

#define COLL_SHARM_ALLGATHER_ALG_CICO  1
#define COLL_SHARM_ALLGATHER_ALG_CMA   11
#define COLL_SHARM_ALLGATHER_ALG_XPMEM 21

#define COLL_SHARM_ALLGATHERV_ALG_CICO  1
#define COLL_SHARM_ALLGATHERV_ALG_CMA   11
#define COLL_SHARM_ALLGATHERV_ALG_XPMEM 21

#define COLL_SHARM_ALLTOALL_ALG_PAIRWISE 1
#define COLL_SHARM_ALLTOALL_ALG_CMA      11
#define COLL_SHARM_ALLTOALL_ALG_XPMEM    21

#define COLL_SHARM_ALLTOALLV_ALG_PAIRWISE 1
#define COLL_SHARM_ALLTOALLV_ALG_CMA      11
#define COLL_SHARM_ALLTOALLV_ALG_XPMEM    21

#define COLL_SHARM_ALLTOALLW_ALG_PAIRWISE 1
#define COLL_SHARM_ALLTOALLW_ALG_CMA      11
#define COLL_SHARM_ALLTOALLW_ALG_XPMEM    21

#endif /* MCA_COLL_SHARM_DATATYPE_H */
